/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as MentionsLegalesRouteImport } from './routes/mentions-legales'
import { Route as CookiesRouteImport } from './routes/cookies'
import { Route as ConfidentialiteRouteImport } from './routes/confidentialite'
import { Route as ChercherUnVehiculeRouteImport } from './routes/chercher-un-vehicule'
import { Route as CgvRouteImport } from './routes/cgv'
import { Route as CguRouteImport } from './routes/cgu'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VehiculesIndexRouteImport } from './routes/vehicules.index'
import { Route as ChercherUnVehiculeIndexRouteImport } from './routes/chercher-un-vehicule.index'
import { Route as VehiculesIdRouteImport } from './routes/vehicules.$id'
import { Route as ChercherUnVehiculeMerciRouteImport } from './routes/chercher-un-vehicule.merci'
import { Route as AuthenticatedSalesRouteImport } from './routes/_authenticated/sales'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedMonLienRouteImport } from './routes/_authenticated/mon-lien'
import { Route as AuthenticatedMesEchangesRouteImport } from './routes/_authenticated/mes-echanges'
import { Route as AuthenticatedMesDemandesClientsRouteImport } from './routes/_authenticated/mes-demandes-clients'
import { Route as AuthenticatedMesDemandesRouteImport } from './routes/_authenticated/mes-demandes'
import { Route as AuthenticatedMesCommissionsRouteImport } from './routes/_authenticated/mes-commissions'
import { Route as AuthenticatedManagerRouteImport } from './routes/_authenticated/manager'
import { Route as AuthenticatedEspaceAcheteurRouteImport } from './routes/_authenticated/espace-acheteur'
import { Route as AuthenticatedDirectionRouteImport } from './routes/_authenticated/direction'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedSalesIndexRouteImport } from './routes/_authenticated/sales.index'
import { Route as AuthenticatedManagerIndexRouteImport } from './routes/_authenticated/manager.index'
import { Route as AuthenticatedDirectionIndexRouteImport } from './routes/_authenticated/direction.index'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as ApiPublicSignupCheckRouteImport } from './routes/api/public/signup-check'
import { Route as ApiPublicBuyerLeadsRouteImport } from './routes/api/public/buyer-leads'
import { Route as ApiPublicAssistantRouteImport } from './routes/api/public/assistant'
import { Route as ApiPublicAffiliateClickRouteImport } from './routes/api/public/affiliate-click'
import { Route as AuthenticatedOpportunitiesNewRouteImport } from './routes/_authenticated/opportunities.new'
import { Route as AuthenticatedOpportunitiesIdRouteImport } from './routes/_authenticated/opportunities.$id'
import { Route as AuthenticatedAdminUsersRouteImport } from './routes/_authenticated/admin.users'
import { Route as AuthenticatedAdminSettingsRouteImport } from './routes/_authenticated/admin.settings'
import { Route as AuthenticatedAdminSaleListingsRouteImport } from './routes/_authenticated/admin.sale-listings'
import { Route as AuthenticatedAdminReferenceRouteImport } from './routes/_authenticated/admin.reference'
import { Route as AuthenticatedAdminPartenairesRouteImport } from './routes/_authenticated/admin.partenaires'
import { Route as AuthenticatedAdminNotificationsRouteImport } from './routes/_authenticated/admin.notifications'
import { Route as AuthenticatedAdminMatchingRouteImport } from './routes/_authenticated/admin.matching'
import { Route as AuthenticatedAdminLeadsRouteImport } from './routes/_authenticated/admin.leads'
import { Route as AuthenticatedAdminContentRouteImport } from './routes/_authenticated/admin.content'
import { Route as AuthenticatedAdminCommissionsRouteImport } from './routes/_authenticated/admin.commissions'
import { Route as AuthenticatedAdminBuyerLeadsRouteImport } from './routes/_authenticated/admin.buyer-leads'
import { Route as AuthenticatedAdminAuditRouteImport } from './routes/_authenticated/admin.audit'
import { Route as AuthenticatedAdminAffiliationRouteImport } from './routes/_authenticated/admin.affiliation'
import { Route as AuthenticatedAdminSaleListingsIndexRouteImport } from './routes/_authenticated/admin.sale-listings.index'
import { Route as AuthenticatedAdminDemandOpportunitiesIndexRouteImport } from './routes/_authenticated/admin.demand-opportunities.index'
import { Route as AuthenticatedAdminBuyerLeadsIndexRouteImport } from './routes/_authenticated/admin.buyer-leads.index'
import { Route as AuthenticatedOpportunitiesSuccessIdRouteImport } from './routes/_authenticated/opportunities.success.$id'
import { Route as AuthenticatedAdminSaleListingsIdRouteImport } from './routes/_authenticated/admin.sale-listings.$id'
import { Route as AuthenticatedAdminOpportunitiesIdRouteImport } from './routes/_authenticated/admin.opportunities.$id'
import { Route as AuthenticatedAdminDemandOpportunitiesIdRouteImport } from './routes/_authenticated/admin.demand-opportunities.$id'
import { Route as AuthenticatedAdminBuyerLeadsIdRouteImport } from './routes/_authenticated/admin.buyer-leads.$id'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const MentionsLegalesRoute = MentionsLegalesRouteImport.update({
  id: '/mentions-legales',
  path: '/mentions-legales',
  getParentRoute: () => rootRouteImport,
} as any)
const CookiesRoute = CookiesRouteImport.update({
  id: '/cookies',
  path: '/cookies',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfidentialiteRoute = ConfidentialiteRouteImport.update({
  id: '/confidentialite',
  path: '/confidentialite',
  getParentRoute: () => rootRouteImport,
} as any)
const ChercherUnVehiculeRoute = ChercherUnVehiculeRouteImport.update({
  id: '/chercher-un-vehicule',
  path: '/chercher-un-vehicule',
  getParentRoute: () => rootRouteImport,
} as any)
const CgvRoute = CgvRouteImport.update({
  id: '/cgv',
  path: '/cgv',
  getParentRoute: () => rootRouteImport,
} as any)
const CguRoute = CguRouteImport.update({
  id: '/cgu',
  path: '/cgu',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VehiculesIndexRoute = VehiculesIndexRouteImport.update({
  id: '/vehicules/',
  path: '/vehicules/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChercherUnVehiculeIndexRoute = ChercherUnVehiculeIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ChercherUnVehiculeRoute,
} as any)
const VehiculesIdRoute = VehiculesIdRouteImport.update({
  id: '/vehicules/$id',
  path: '/vehicules/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ChercherUnVehiculeMerciRoute = ChercherUnVehiculeMerciRouteImport.update({
  id: '/merci',
  path: '/merci',
  getParentRoute: () => ChercherUnVehiculeRoute,
} as any)
const AuthenticatedSalesRoute = AuthenticatedSalesRouteImport.update({
  id: '/sales',
  path: '/sales',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMonLienRoute = AuthenticatedMonLienRouteImport.update({
  id: '/mon-lien',
  path: '/mon-lien',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMesEchangesRoute =
  AuthenticatedMesEchangesRouteImport.update({
    id: '/mes-echanges',
    path: '/mes-echanges',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMesDemandesClientsRoute =
  AuthenticatedMesDemandesClientsRouteImport.update({
    id: '/mes-demandes-clients',
    path: '/mes-demandes-clients',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMesDemandesRoute =
  AuthenticatedMesDemandesRouteImport.update({
    id: '/mes-demandes',
    path: '/mes-demandes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMesCommissionsRoute =
  AuthenticatedMesCommissionsRouteImport.update({
    id: '/mes-commissions',
    path: '/mes-commissions',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedManagerRoute = AuthenticatedManagerRouteImport.update({
  id: '/manager',
  path: '/manager',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEspaceAcheteurRoute =
  AuthenticatedEspaceAcheteurRouteImport.update({
    id: '/espace-acheteur',
    path: '/espace-acheteur',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDirectionRoute = AuthenticatedDirectionRouteImport.update({
  id: '/direction',
  path: '/direction',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSalesIndexRoute = AuthenticatedSalesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedSalesRoute,
} as any)
const AuthenticatedManagerIndexRoute =
  AuthenticatedManagerIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedManagerRoute,
  } as any)
const AuthenticatedDirectionIndexRoute =
  AuthenticatedDirectionIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedDirectionRoute,
  } as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const ApiPublicSignupCheckRoute = ApiPublicSignupCheckRouteImport.update({
  id: '/api/public/signup-check',
  path: '/api/public/signup-check',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicBuyerLeadsRoute = ApiPublicBuyerLeadsRouteImport.update({
  id: '/api/public/buyer-leads',
  path: '/api/public/buyer-leads',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAssistantRoute = ApiPublicAssistantRouteImport.update({
  id: '/api/public/assistant',
  path: '/api/public/assistant',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAffiliateClickRoute = ApiPublicAffiliateClickRouteImport.update({
  id: '/api/public/affiliate-click',
  path: '/api/public/affiliate-click',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedOpportunitiesNewRoute =
  AuthenticatedOpportunitiesNewRouteImport.update({
    id: '/opportunities/new',
    path: '/opportunities/new',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOpportunitiesIdRoute =
  AuthenticatedOpportunitiesIdRouteImport.update({
    id: '/opportunities/$id',
    path: '/opportunities/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminUsersRoute = AuthenticatedAdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminSettingsRoute =
  AuthenticatedAdminSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminSaleListingsRoute =
  AuthenticatedAdminSaleListingsRouteImport.update({
    id: '/sale-listings',
    path: '/sale-listings',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminReferenceRoute =
  AuthenticatedAdminReferenceRouteImport.update({
    id: '/reference',
    path: '/reference',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminPartenairesRoute =
  AuthenticatedAdminPartenairesRouteImport.update({
    id: '/partenaires',
    path: '/partenaires',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminNotificationsRoute =
  AuthenticatedAdminNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminMatchingRoute =
  AuthenticatedAdminMatchingRouteImport.update({
    id: '/matching',
    path: '/matching',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminLeadsRoute = AuthenticatedAdminLeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminContentRoute =
  AuthenticatedAdminContentRouteImport.update({
    id: '/content',
    path: '/content',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminCommissionsRoute =
  AuthenticatedAdminCommissionsRouteImport.update({
    id: '/commissions',
    path: '/commissions',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminBuyerLeadsRoute =
  AuthenticatedAdminBuyerLeadsRouteImport.update({
    id: '/buyer-leads',
    path: '/buyer-leads',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminAuditRoute = AuthenticatedAdminAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminAffiliationRoute =
  AuthenticatedAdminAffiliationRouteImport.update({
    id: '/affiliation',
    path: '/affiliation',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminSaleListingsIndexRoute =
  AuthenticatedAdminSaleListingsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAdminSaleListingsRoute,
  } as any)
const AuthenticatedAdminDemandOpportunitiesIndexRoute =
  AuthenticatedAdminDemandOpportunitiesIndexRouteImport.update({
    id: '/demand-opportunities/',
    path: '/demand-opportunities/',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminBuyerLeadsIndexRoute =
  AuthenticatedAdminBuyerLeadsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAdminBuyerLeadsRoute,
  } as any)
const AuthenticatedOpportunitiesSuccessIdRoute =
  AuthenticatedOpportunitiesSuccessIdRouteImport.update({
    id: '/opportunities/success/$id',
    path: '/opportunities/success/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminSaleListingsIdRoute =
  AuthenticatedAdminSaleListingsIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedAdminSaleListingsRoute,
  } as any)
const AuthenticatedAdminOpportunitiesIdRoute =
  AuthenticatedAdminOpportunitiesIdRouteImport.update({
    id: '/opportunities/$id',
    path: '/opportunities/$id',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminDemandOpportunitiesIdRoute =
  AuthenticatedAdminDemandOpportunitiesIdRouteImport.update({
    id: '/demand-opportunities/$id',
    path: '/demand-opportunities/$id',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminBuyerLeadsIdRoute =
  AuthenticatedAdminBuyerLeadsIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedAdminBuyerLeadsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/cgu': typeof CguRoute
  '/cgv': typeof CgvRoute
  '/chercher-un-vehicule': typeof ChercherUnVehiculeRouteWithChildren
  '/confidentialite': typeof ConfidentialiteRoute
  '/cookies': typeof CookiesRoute
  '/mentions-legales': typeof MentionsLegalesRoute
  '/reset-password': typeof ResetPasswordRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/direction': typeof AuthenticatedDirectionRouteWithChildren
  '/espace-acheteur': typeof AuthenticatedEspaceAcheteurRoute
  '/manager': typeof AuthenticatedManagerRouteWithChildren
  '/mes-commissions': typeof AuthenticatedMesCommissionsRoute
  '/mes-demandes': typeof AuthenticatedMesDemandesRoute
  '/mes-demandes-clients': typeof AuthenticatedMesDemandesClientsRoute
  '/mes-echanges': typeof AuthenticatedMesEchangesRoute
  '/mon-lien': typeof AuthenticatedMonLienRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/sales': typeof AuthenticatedSalesRouteWithChildren
  '/chercher-un-vehicule/merci': typeof ChercherUnVehiculeMerciRoute
  '/vehicules/$id': typeof VehiculesIdRoute
  '/chercher-un-vehicule/': typeof ChercherUnVehiculeIndexRoute
  '/vehicules/': typeof VehiculesIndexRoute
  '/admin/affiliation': typeof AuthenticatedAdminAffiliationRoute
  '/admin/audit': typeof AuthenticatedAdminAuditRoute
  '/admin/buyer-leads': typeof AuthenticatedAdminBuyerLeadsRouteWithChildren
  '/admin/commissions': typeof AuthenticatedAdminCommissionsRoute
  '/admin/content': typeof AuthenticatedAdminContentRoute
  '/admin/leads': typeof AuthenticatedAdminLeadsRoute
  '/admin/matching': typeof AuthenticatedAdminMatchingRoute
  '/admin/notifications': typeof AuthenticatedAdminNotificationsRoute
  '/admin/partenaires': typeof AuthenticatedAdminPartenairesRoute
  '/admin/reference': typeof AuthenticatedAdminReferenceRoute
  '/admin/sale-listings': typeof AuthenticatedAdminSaleListingsRouteWithChildren
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/opportunities/$id': typeof AuthenticatedOpportunitiesIdRoute
  '/opportunities/new': typeof AuthenticatedOpportunitiesNewRoute
  '/api/public/affiliate-click': typeof ApiPublicAffiliateClickRoute
  '/api/public/assistant': typeof ApiPublicAssistantRoute
  '/api/public/buyer-leads': typeof ApiPublicBuyerLeadsRoute
  '/api/public/signup-check': typeof ApiPublicSignupCheckRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/direction/': typeof AuthenticatedDirectionIndexRoute
  '/manager/': typeof AuthenticatedManagerIndexRoute
  '/sales/': typeof AuthenticatedSalesIndexRoute
  '/admin/buyer-leads/$id': typeof AuthenticatedAdminBuyerLeadsIdRoute
  '/admin/demand-opportunities/$id': typeof AuthenticatedAdminDemandOpportunitiesIdRoute
  '/admin/opportunities/$id': typeof AuthenticatedAdminOpportunitiesIdRoute
  '/admin/sale-listings/$id': typeof AuthenticatedAdminSaleListingsIdRoute
  '/opportunities/success/$id': typeof AuthenticatedOpportunitiesSuccessIdRoute
  '/admin/buyer-leads/': typeof AuthenticatedAdminBuyerLeadsIndexRoute
  '/admin/demand-opportunities/': typeof AuthenticatedAdminDemandOpportunitiesIndexRoute
  '/admin/sale-listings/': typeof AuthenticatedAdminSaleListingsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/cgu': typeof CguRoute
  '/cgv': typeof CgvRoute
  '/confidentialite': typeof ConfidentialiteRoute
  '/cookies': typeof CookiesRoute
  '/mentions-legales': typeof MentionsLegalesRoute
  '/reset-password': typeof ResetPasswordRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/espace-acheteur': typeof AuthenticatedEspaceAcheteurRoute
  '/mes-commissions': typeof AuthenticatedMesCommissionsRoute
  '/mes-demandes': typeof AuthenticatedMesDemandesRoute
  '/mes-demandes-clients': typeof AuthenticatedMesDemandesClientsRoute
  '/mes-echanges': typeof AuthenticatedMesEchangesRoute
  '/mon-lien': typeof AuthenticatedMonLienRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/chercher-un-vehicule/merci': typeof ChercherUnVehiculeMerciRoute
  '/vehicules/$id': typeof VehiculesIdRoute
  '/chercher-un-vehicule': typeof ChercherUnVehiculeIndexRoute
  '/vehicules': typeof VehiculesIndexRoute
  '/admin/affiliation': typeof AuthenticatedAdminAffiliationRoute
  '/admin/audit': typeof AuthenticatedAdminAuditRoute
  '/admin/commissions': typeof AuthenticatedAdminCommissionsRoute
  '/admin/content': typeof AuthenticatedAdminContentRoute
  '/admin/leads': typeof AuthenticatedAdminLeadsRoute
  '/admin/matching': typeof AuthenticatedAdminMatchingRoute
  '/admin/notifications': typeof AuthenticatedAdminNotificationsRoute
  '/admin/partenaires': typeof AuthenticatedAdminPartenairesRoute
  '/admin/reference': typeof AuthenticatedAdminReferenceRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/opportunities/$id': typeof AuthenticatedOpportunitiesIdRoute
  '/opportunities/new': typeof AuthenticatedOpportunitiesNewRoute
  '/api/public/affiliate-click': typeof ApiPublicAffiliateClickRoute
  '/api/public/assistant': typeof ApiPublicAssistantRoute
  '/api/public/buyer-leads': typeof ApiPublicBuyerLeadsRoute
  '/api/public/signup-check': typeof ApiPublicSignupCheckRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/direction': typeof AuthenticatedDirectionIndexRoute
  '/manager': typeof AuthenticatedManagerIndexRoute
  '/sales': typeof AuthenticatedSalesIndexRoute
  '/admin/buyer-leads/$id': typeof AuthenticatedAdminBuyerLeadsIdRoute
  '/admin/demand-opportunities/$id': typeof AuthenticatedAdminDemandOpportunitiesIdRoute
  '/admin/opportunities/$id': typeof AuthenticatedAdminOpportunitiesIdRoute
  '/admin/sale-listings/$id': typeof AuthenticatedAdminSaleListingsIdRoute
  '/opportunities/success/$id': typeof AuthenticatedOpportunitiesSuccessIdRoute
  '/admin/buyer-leads': typeof AuthenticatedAdminBuyerLeadsIndexRoute
  '/admin/demand-opportunities': typeof AuthenticatedAdminDemandOpportunitiesIndexRoute
  '/admin/sale-listings': typeof AuthenticatedAdminSaleListingsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/cgu': typeof CguRoute
  '/cgv': typeof CgvRoute
  '/chercher-un-vehicule': typeof ChercherUnVehiculeRouteWithChildren
  '/confidentialite': typeof ConfidentialiteRoute
  '/cookies': typeof CookiesRoute
  '/mentions-legales': typeof MentionsLegalesRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/direction': typeof AuthenticatedDirectionRouteWithChildren
  '/_authenticated/espace-acheteur': typeof AuthenticatedEspaceAcheteurRoute
  '/_authenticated/manager': typeof AuthenticatedManagerRouteWithChildren
  '/_authenticated/mes-commissions': typeof AuthenticatedMesCommissionsRoute
  '/_authenticated/mes-demandes': typeof AuthenticatedMesDemandesRoute
  '/_authenticated/mes-demandes-clients': typeof AuthenticatedMesDemandesClientsRoute
  '/_authenticated/mes-echanges': typeof AuthenticatedMesEchangesRoute
  '/_authenticated/mon-lien': typeof AuthenticatedMonLienRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/sales': typeof AuthenticatedSalesRouteWithChildren
  '/chercher-un-vehicule/merci': typeof ChercherUnVehiculeMerciRoute
  '/vehicules/$id': typeof VehiculesIdRoute
  '/chercher-un-vehicule/': typeof ChercherUnVehiculeIndexRoute
  '/vehicules/': typeof VehiculesIndexRoute
  '/_authenticated/admin/affiliation': typeof AuthenticatedAdminAffiliationRoute
  '/_authenticated/admin/audit': typeof AuthenticatedAdminAuditRoute
  '/_authenticated/admin/buyer-leads': typeof AuthenticatedAdminBuyerLeadsRouteWithChildren
  '/_authenticated/admin/commissions': typeof AuthenticatedAdminCommissionsRoute
  '/_authenticated/admin/content': typeof AuthenticatedAdminContentRoute
  '/_authenticated/admin/leads': typeof AuthenticatedAdminLeadsRoute
  '/_authenticated/admin/matching': typeof AuthenticatedAdminMatchingRoute
  '/_authenticated/admin/notifications': typeof AuthenticatedAdminNotificationsRoute
  '/_authenticated/admin/partenaires': typeof AuthenticatedAdminPartenairesRoute
  '/_authenticated/admin/reference': typeof AuthenticatedAdminReferenceRoute
  '/_authenticated/admin/sale-listings': typeof AuthenticatedAdminSaleListingsRouteWithChildren
  '/_authenticated/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/_authenticated/admin/users': typeof AuthenticatedAdminUsersRoute
  '/_authenticated/opportunities/$id': typeof AuthenticatedOpportunitiesIdRoute
  '/_authenticated/opportunities/new': typeof AuthenticatedOpportunitiesNewRoute
  '/api/public/affiliate-click': typeof ApiPublicAffiliateClickRoute
  '/api/public/assistant': typeof ApiPublicAssistantRoute
  '/api/public/buyer-leads': typeof ApiPublicBuyerLeadsRoute
  '/api/public/signup-check': typeof ApiPublicSignupCheckRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/direction/': typeof AuthenticatedDirectionIndexRoute
  '/_authenticated/manager/': typeof AuthenticatedManagerIndexRoute
  '/_authenticated/sales/': typeof AuthenticatedSalesIndexRoute
  '/_authenticated/admin/buyer-leads/$id': typeof AuthenticatedAdminBuyerLeadsIdRoute
  '/_authenticated/admin/demand-opportunities/$id': typeof AuthenticatedAdminDemandOpportunitiesIdRoute
  '/_authenticated/admin/opportunities/$id': typeof AuthenticatedAdminOpportunitiesIdRoute
  '/_authenticated/admin/sale-listings/$id': typeof AuthenticatedAdminSaleListingsIdRoute
  '/_authenticated/opportunities/success/$id': typeof AuthenticatedOpportunitiesSuccessIdRoute
  '/_authenticated/admin/buyer-leads/': typeof AuthenticatedAdminBuyerLeadsIndexRoute
  '/_authenticated/admin/demand-opportunities/': typeof AuthenticatedAdminDemandOpportunitiesIndexRoute
  '/_authenticated/admin/sale-listings/': typeof AuthenticatedAdminSaleListingsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/cgu'
    | '/cgv'
    | '/chercher-un-vehicule'
    | '/confidentialite'
    | '/cookies'
    | '/mentions-legales'
    | '/reset-password'
    | '/admin'
    | '/dashboard'
    | '/direction'
    | '/espace-acheteur'
    | '/manager'
    | '/mes-commissions'
    | '/mes-demandes'
    | '/mes-demandes-clients'
    | '/mes-echanges'
    | '/mon-lien'
    | '/profile'
    | '/sales'
    | '/chercher-un-vehicule/merci'
    | '/vehicules/$id'
    | '/chercher-un-vehicule/'
    | '/vehicules/'
    | '/admin/affiliation'
    | '/admin/audit'
    | '/admin/buyer-leads'
    | '/admin/commissions'
    | '/admin/content'
    | '/admin/leads'
    | '/admin/matching'
    | '/admin/notifications'
    | '/admin/partenaires'
    | '/admin/reference'
    | '/admin/sale-listings'
    | '/admin/settings'
    | '/admin/users'
    | '/opportunities/$id'
    | '/opportunities/new'
    | '/api/public/affiliate-click'
    | '/api/public/assistant'
    | '/api/public/buyer-leads'
    | '/api/public/signup-check'
    | '/admin/'
    | '/direction/'
    | '/manager/'
    | '/sales/'
    | '/admin/buyer-leads/$id'
    | '/admin/demand-opportunities/$id'
    | '/admin/opportunities/$id'
    | '/admin/sale-listings/$id'
    | '/opportunities/success/$id'
    | '/admin/buyer-leads/'
    | '/admin/demand-opportunities/'
    | '/admin/sale-listings/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/cgu'
    | '/cgv'
    | '/confidentialite'
    | '/cookies'
    | '/mentions-legales'
    | '/reset-password'
    | '/dashboard'
    | '/espace-acheteur'
    | '/mes-commissions'
    | '/mes-demandes'
    | '/mes-demandes-clients'
    | '/mes-echanges'
    | '/mon-lien'
    | '/profile'
    | '/chercher-un-vehicule/merci'
    | '/vehicules/$id'
    | '/chercher-un-vehicule'
    | '/vehicules'
    | '/admin/affiliation'
    | '/admin/audit'
    | '/admin/commissions'
    | '/admin/content'
    | '/admin/leads'
    | '/admin/matching'
    | '/admin/notifications'
    | '/admin/partenaires'
    | '/admin/reference'
    | '/admin/settings'
    | '/admin/users'
    | '/opportunities/$id'
    | '/opportunities/new'
    | '/api/public/affiliate-click'
    | '/api/public/assistant'
    | '/api/public/buyer-leads'
    | '/api/public/signup-check'
    | '/admin'
    | '/direction'
    | '/manager'
    | '/sales'
    | '/admin/buyer-leads/$id'
    | '/admin/demand-opportunities/$id'
    | '/admin/opportunities/$id'
    | '/admin/sale-listings/$id'
    | '/opportunities/success/$id'
    | '/admin/buyer-leads'
    | '/admin/demand-opportunities'
    | '/admin/sale-listings'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/cgu'
    | '/cgv'
    | '/chercher-un-vehicule'
    | '/confidentialite'
    | '/cookies'
    | '/mentions-legales'
    | '/reset-password'
    | '/_authenticated/admin'
    | '/_authenticated/dashboard'
    | '/_authenticated/direction'
    | '/_authenticated/espace-acheteur'
    | '/_authenticated/manager'
    | '/_authenticated/mes-commissions'
    | '/_authenticated/mes-demandes'
    | '/_authenticated/mes-demandes-clients'
    | '/_authenticated/mes-echanges'
    | '/_authenticated/mon-lien'
    | '/_authenticated/profile'
    | '/_authenticated/sales'
    | '/chercher-un-vehicule/merci'
    | '/vehicules/$id'
    | '/chercher-un-vehicule/'
    | '/vehicules/'
    | '/_authenticated/admin/affiliation'
    | '/_authenticated/admin/audit'
    | '/_authenticated/admin/buyer-leads'
    | '/_authenticated/admin/commissions'
    | '/_authenticated/admin/content'
    | '/_authenticated/admin/leads'
    | '/_authenticated/admin/matching'
    | '/_authenticated/admin/notifications'
    | '/_authenticated/admin/partenaires'
    | '/_authenticated/admin/reference'
    | '/_authenticated/admin/sale-listings'
    | '/_authenticated/admin/settings'
    | '/_authenticated/admin/users'
    | '/_authenticated/opportunities/$id'
    | '/_authenticated/opportunities/new'
    | '/api/public/affiliate-click'
    | '/api/public/assistant'
    | '/api/public/buyer-leads'
    | '/api/public/signup-check'
    | '/_authenticated/admin/'
    | '/_authenticated/direction/'
    | '/_authenticated/manager/'
    | '/_authenticated/sales/'
    | '/_authenticated/admin/buyer-leads/$id'
    | '/_authenticated/admin/demand-opportunities/$id'
    | '/_authenticated/admin/opportunities/$id'
    | '/_authenticated/admin/sale-listings/$id'
    | '/_authenticated/opportunities/success/$id'
    | '/_authenticated/admin/buyer-leads/'
    | '/_authenticated/admin/demand-opportunities/'
    | '/_authenticated/admin/sale-listings/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  CguRoute: typeof CguRoute
  CgvRoute: typeof CgvRoute
  ChercherUnVehiculeRoute: typeof ChercherUnVehiculeRouteWithChildren
  ConfidentialiteRoute: typeof ConfidentialiteRoute
  CookiesRoute: typeof CookiesRoute
  MentionsLegalesRoute: typeof MentionsLegalesRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  VehiculesIdRoute: typeof VehiculesIdRoute
  VehiculesIndexRoute: typeof VehiculesIndexRoute
  ApiPublicAffiliateClickRoute: typeof ApiPublicAffiliateClickRoute
  ApiPublicAssistantRoute: typeof ApiPublicAssistantRoute
  ApiPublicBuyerLeadsRoute: typeof ApiPublicBuyerLeadsRoute
  ApiPublicSignupCheckRoute: typeof ApiPublicSignupCheckRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mentions-legales': {
      id: '/mentions-legales'
      path: '/mentions-legales'
      fullPath: '/mentions-legales'
      preLoaderRoute: typeof MentionsLegalesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookies': {
      id: '/cookies'
      path: '/cookies'
      fullPath: '/cookies'
      preLoaderRoute: typeof CookiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/confidentialite': {
      id: '/confidentialite'
      path: '/confidentialite'
      fullPath: '/confidentialite'
      preLoaderRoute: typeof ConfidentialiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chercher-un-vehicule': {
      id: '/chercher-un-vehicule'
      path: '/chercher-un-vehicule'
      fullPath: '/chercher-un-vehicule'
      preLoaderRoute: typeof ChercherUnVehiculeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cgv': {
      id: '/cgv'
      path: '/cgv'
      fullPath: '/cgv'
      preLoaderRoute: typeof CgvRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cgu': {
      id: '/cgu'
      path: '/cgu'
      fullPath: '/cgu'
      preLoaderRoute: typeof CguRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vehicules/': {
      id: '/vehicules/'
      path: '/vehicules'
      fullPath: '/vehicules/'
      preLoaderRoute: typeof VehiculesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chercher-un-vehicule/': {
      id: '/chercher-un-vehicule/'
      path: '/'
      fullPath: '/chercher-un-vehicule/'
      preLoaderRoute: typeof ChercherUnVehiculeIndexRouteImport
      parentRoute: typeof ChercherUnVehiculeRoute
    }
    '/vehicules/$id': {
      id: '/vehicules/$id'
      path: '/vehicules/$id'
      fullPath: '/vehicules/$id'
      preLoaderRoute: typeof VehiculesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chercher-un-vehicule/merci': {
      id: '/chercher-un-vehicule/merci'
      path: '/merci'
      fullPath: '/chercher-un-vehicule/merci'
      preLoaderRoute: typeof ChercherUnVehiculeMerciRouteImport
      parentRoute: typeof ChercherUnVehiculeRoute
    }
    '/_authenticated/sales': {
      id: '/_authenticated/sales'
      path: '/sales'
      fullPath: '/sales'
      preLoaderRoute: typeof AuthenticatedSalesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/mon-lien': {
      id: '/_authenticated/mon-lien'
      path: '/mon-lien'
      fullPath: '/mon-lien'
      preLoaderRoute: typeof AuthenticatedMonLienRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/mes-echanges': {
      id: '/_authenticated/mes-echanges'
      path: '/mes-echanges'
      fullPath: '/mes-echanges'
      preLoaderRoute: typeof AuthenticatedMesEchangesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/mes-demandes-clients': {
      id: '/_authenticated/mes-demandes-clients'
      path: '/mes-demandes-clients'
      fullPath: '/mes-demandes-clients'
      preLoaderRoute: typeof AuthenticatedMesDemandesClientsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/mes-demandes': {
      id: '/_authenticated/mes-demandes'
      path: '/mes-demandes'
      fullPath: '/mes-demandes'
      preLoaderRoute: typeof AuthenticatedMesDemandesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/mes-commissions': {
      id: '/_authenticated/mes-commissions'
      path: '/mes-commissions'
      fullPath: '/mes-commissions'
      preLoaderRoute: typeof AuthenticatedMesCommissionsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/manager': {
      id: '/_authenticated/manager'
      path: '/manager'
      fullPath: '/manager'
      preLoaderRoute: typeof AuthenticatedManagerRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/espace-acheteur': {
      id: '/_authenticated/espace-acheteur'
      path: '/espace-acheteur'
      fullPath: '/espace-acheteur'
      preLoaderRoute: typeof AuthenticatedEspaceAcheteurRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/direction': {
      id: '/_authenticated/direction'
      path: '/direction'
      fullPath: '/direction'
      preLoaderRoute: typeof AuthenticatedDirectionRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sales/': {
      id: '/_authenticated/sales/'
      path: '/'
      fullPath: '/sales/'
      preLoaderRoute: typeof AuthenticatedSalesIndexRouteImport
      parentRoute: typeof AuthenticatedSalesRoute
    }
    '/_authenticated/manager/': {
      id: '/_authenticated/manager/'
      path: '/'
      fullPath: '/manager/'
      preLoaderRoute: typeof AuthenticatedManagerIndexRouteImport
      parentRoute: typeof AuthenticatedManagerRoute
    }
    '/_authenticated/direction/': {
      id: '/_authenticated/direction/'
      path: '/'
      fullPath: '/direction/'
      preLoaderRoute: typeof AuthenticatedDirectionIndexRouteImport
      parentRoute: typeof AuthenticatedDirectionRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/api/public/signup-check': {
      id: '/api/public/signup-check'
      path: '/api/public/signup-check'
      fullPath: '/api/public/signup-check'
      preLoaderRoute: typeof ApiPublicSignupCheckRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/buyer-leads': {
      id: '/api/public/buyer-leads'
      path: '/api/public/buyer-leads'
      fullPath: '/api/public/buyer-leads'
      preLoaderRoute: typeof ApiPublicBuyerLeadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/assistant': {
      id: '/api/public/assistant'
      path: '/api/public/assistant'
      fullPath: '/api/public/assistant'
      preLoaderRoute: typeof ApiPublicAssistantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/affiliate-click': {
      id: '/api/public/affiliate-click'
      path: '/api/public/affiliate-click'
      fullPath: '/api/public/affiliate-click'
      preLoaderRoute: typeof ApiPublicAffiliateClickRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/opportunities/new': {
      id: '/_authenticated/opportunities/new'
      path: '/opportunities/new'
      fullPath: '/opportunities/new'
      preLoaderRoute: typeof AuthenticatedOpportunitiesNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/opportunities/$id': {
      id: '/_authenticated/opportunities/$id'
      path: '/opportunities/$id'
      fullPath: '/opportunities/$id'
      preLoaderRoute: typeof AuthenticatedOpportunitiesIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/users': {
      id: '/_authenticated/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthenticatedAdminUsersRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/settings': {
      id: '/_authenticated/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AuthenticatedAdminSettingsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/sale-listings': {
      id: '/_authenticated/admin/sale-listings'
      path: '/sale-listings'
      fullPath: '/admin/sale-listings'
      preLoaderRoute: typeof AuthenticatedAdminSaleListingsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/reference': {
      id: '/_authenticated/admin/reference'
      path: '/reference'
      fullPath: '/admin/reference'
      preLoaderRoute: typeof AuthenticatedAdminReferenceRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/partenaires': {
      id: '/_authenticated/admin/partenaires'
      path: '/partenaires'
      fullPath: '/admin/partenaires'
      preLoaderRoute: typeof AuthenticatedAdminPartenairesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/notifications': {
      id: '/_authenticated/admin/notifications'
      path: '/notifications'
      fullPath: '/admin/notifications'
      preLoaderRoute: typeof AuthenticatedAdminNotificationsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/matching': {
      id: '/_authenticated/admin/matching'
      path: '/matching'
      fullPath: '/admin/matching'
      preLoaderRoute: typeof AuthenticatedAdminMatchingRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/leads': {
      id: '/_authenticated/admin/leads'
      path: '/leads'
      fullPath: '/admin/leads'
      preLoaderRoute: typeof AuthenticatedAdminLeadsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/content': {
      id: '/_authenticated/admin/content'
      path: '/content'
      fullPath: '/admin/content'
      preLoaderRoute: typeof AuthenticatedAdminContentRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/commissions': {
      id: '/_authenticated/admin/commissions'
      path: '/commissions'
      fullPath: '/admin/commissions'
      preLoaderRoute: typeof AuthenticatedAdminCommissionsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/buyer-leads': {
      id: '/_authenticated/admin/buyer-leads'
      path: '/buyer-leads'
      fullPath: '/admin/buyer-leads'
      preLoaderRoute: typeof AuthenticatedAdminBuyerLeadsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/audit': {
      id: '/_authenticated/admin/audit'
      path: '/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AuthenticatedAdminAuditRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/affiliation': {
      id: '/_authenticated/admin/affiliation'
      path: '/affiliation'
      fullPath: '/admin/affiliation'
      preLoaderRoute: typeof AuthenticatedAdminAffiliationRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/sale-listings/': {
      id: '/_authenticated/admin/sale-listings/'
      path: '/'
      fullPath: '/admin/sale-listings/'
      preLoaderRoute: typeof AuthenticatedAdminSaleListingsIndexRouteImport
      parentRoute: typeof AuthenticatedAdminSaleListingsRoute
    }
    '/_authenticated/admin/demand-opportunities/': {
      id: '/_authenticated/admin/demand-opportunities/'
      path: '/demand-opportunities'
      fullPath: '/admin/demand-opportunities/'
      preLoaderRoute: typeof AuthenticatedAdminDemandOpportunitiesIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/buyer-leads/': {
      id: '/_authenticated/admin/buyer-leads/'
      path: '/'
      fullPath: '/admin/buyer-leads/'
      preLoaderRoute: typeof AuthenticatedAdminBuyerLeadsIndexRouteImport
      parentRoute: typeof AuthenticatedAdminBuyerLeadsRoute
    }
    '/_authenticated/opportunities/success/$id': {
      id: '/_authenticated/opportunities/success/$id'
      path: '/opportunities/success/$id'
      fullPath: '/opportunities/success/$id'
      preLoaderRoute: typeof AuthenticatedOpportunitiesSuccessIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/sale-listings/$id': {
      id: '/_authenticated/admin/sale-listings/$id'
      path: '/$id'
      fullPath: '/admin/sale-listings/$id'
      preLoaderRoute: typeof AuthenticatedAdminSaleListingsIdRouteImport
      parentRoute: typeof AuthenticatedAdminSaleListingsRoute
    }
    '/_authenticated/admin/opportunities/$id': {
      id: '/_authenticated/admin/opportunities/$id'
      path: '/opportunities/$id'
      fullPath: '/admin/opportunities/$id'
      preLoaderRoute: typeof AuthenticatedAdminOpportunitiesIdRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/demand-opportunities/$id': {
      id: '/_authenticated/admin/demand-opportunities/$id'
      path: '/demand-opportunities/$id'
      fullPath: '/admin/demand-opportunities/$id'
      preLoaderRoute: typeof AuthenticatedAdminDemandOpportunitiesIdRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/buyer-leads/$id': {
      id: '/_authenticated/admin/buyer-leads/$id'
      path: '/$id'
      fullPath: '/admin/buyer-leads/$id'
      preLoaderRoute: typeof AuthenticatedAdminBuyerLeadsIdRouteImport
      parentRoute: typeof AuthenticatedAdminBuyerLeadsRoute
    }
  }
}

interface AuthenticatedAdminBuyerLeadsRouteChildren {
  AuthenticatedAdminBuyerLeadsIdRoute: typeof AuthenticatedAdminBuyerLeadsIdRoute
  AuthenticatedAdminBuyerLeadsIndexRoute: typeof AuthenticatedAdminBuyerLeadsIndexRoute
}

const AuthenticatedAdminBuyerLeadsRouteChildren: AuthenticatedAdminBuyerLeadsRouteChildren =
  {
    AuthenticatedAdminBuyerLeadsIdRoute: AuthenticatedAdminBuyerLeadsIdRoute,
    AuthenticatedAdminBuyerLeadsIndexRoute:
      AuthenticatedAdminBuyerLeadsIndexRoute,
  }

const AuthenticatedAdminBuyerLeadsRouteWithChildren =
  AuthenticatedAdminBuyerLeadsRoute._addFileChildren(
    AuthenticatedAdminBuyerLeadsRouteChildren,
  )

interface AuthenticatedAdminSaleListingsRouteChildren {
  AuthenticatedAdminSaleListingsIdRoute: typeof AuthenticatedAdminSaleListingsIdRoute
  AuthenticatedAdminSaleListingsIndexRoute: typeof AuthenticatedAdminSaleListingsIndexRoute
}

const AuthenticatedAdminSaleListingsRouteChildren: AuthenticatedAdminSaleListingsRouteChildren =
  {
    AuthenticatedAdminSaleListingsIdRoute:
      AuthenticatedAdminSaleListingsIdRoute,
    AuthenticatedAdminSaleListingsIndexRoute:
      AuthenticatedAdminSaleListingsIndexRoute,
  }

const AuthenticatedAdminSaleListingsRouteWithChildren =
  AuthenticatedAdminSaleListingsRoute._addFileChildren(
    AuthenticatedAdminSaleListingsRouteChildren,
  )

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminAffiliationRoute: typeof AuthenticatedAdminAffiliationRoute
  AuthenticatedAdminAuditRoute: typeof AuthenticatedAdminAuditRoute
  AuthenticatedAdminBuyerLeadsRoute: typeof AuthenticatedAdminBuyerLeadsRouteWithChildren
  AuthenticatedAdminCommissionsRoute: typeof AuthenticatedAdminCommissionsRoute
  AuthenticatedAdminContentRoute: typeof AuthenticatedAdminContentRoute
  AuthenticatedAdminLeadsRoute: typeof AuthenticatedAdminLeadsRoute
  AuthenticatedAdminMatchingRoute: typeof AuthenticatedAdminMatchingRoute
  AuthenticatedAdminNotificationsRoute: typeof AuthenticatedAdminNotificationsRoute
  AuthenticatedAdminPartenairesRoute: typeof AuthenticatedAdminPartenairesRoute
  AuthenticatedAdminReferenceRoute: typeof AuthenticatedAdminReferenceRoute
  AuthenticatedAdminSaleListingsRoute: typeof AuthenticatedAdminSaleListingsRouteWithChildren
  AuthenticatedAdminSettingsRoute: typeof AuthenticatedAdminSettingsRoute
  AuthenticatedAdminUsersRoute: typeof AuthenticatedAdminUsersRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
  AuthenticatedAdminDemandOpportunitiesIdRoute: typeof AuthenticatedAdminDemandOpportunitiesIdRoute
  AuthenticatedAdminOpportunitiesIdRoute: typeof AuthenticatedAdminOpportunitiesIdRoute
  AuthenticatedAdminDemandOpportunitiesIndexRoute: typeof AuthenticatedAdminDemandOpportunitiesIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminAffiliationRoute: AuthenticatedAdminAffiliationRoute,
  AuthenticatedAdminAuditRoute: AuthenticatedAdminAuditRoute,
  AuthenticatedAdminBuyerLeadsRoute:
    AuthenticatedAdminBuyerLeadsRouteWithChildren,
  AuthenticatedAdminCommissionsRoute: AuthenticatedAdminCommissionsRoute,
  AuthenticatedAdminContentRoute: AuthenticatedAdminContentRoute,
  AuthenticatedAdminLeadsRoute: AuthenticatedAdminLeadsRoute,
  AuthenticatedAdminMatchingRoute: AuthenticatedAdminMatchingRoute,
  AuthenticatedAdminNotificationsRoute: AuthenticatedAdminNotificationsRoute,
  AuthenticatedAdminPartenairesRoute: AuthenticatedAdminPartenairesRoute,
  AuthenticatedAdminReferenceRoute: AuthenticatedAdminReferenceRoute,
  AuthenticatedAdminSaleListingsRoute:
    AuthenticatedAdminSaleListingsRouteWithChildren,
  AuthenticatedAdminSettingsRoute: AuthenticatedAdminSettingsRoute,
  AuthenticatedAdminUsersRoute: AuthenticatedAdminUsersRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  AuthenticatedAdminDemandOpportunitiesIdRoute:
    AuthenticatedAdminDemandOpportunitiesIdRoute,
  AuthenticatedAdminOpportunitiesIdRoute:
    AuthenticatedAdminOpportunitiesIdRoute,
  AuthenticatedAdminDemandOpportunitiesIndexRoute:
    AuthenticatedAdminDemandOpportunitiesIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedDirectionRouteChildren {
  AuthenticatedDirectionIndexRoute: typeof AuthenticatedDirectionIndexRoute
}

const AuthenticatedDirectionRouteChildren: AuthenticatedDirectionRouteChildren =
  {
    AuthenticatedDirectionIndexRoute: AuthenticatedDirectionIndexRoute,
  }

const AuthenticatedDirectionRouteWithChildren =
  AuthenticatedDirectionRoute._addFileChildren(
    AuthenticatedDirectionRouteChildren,
  )

interface AuthenticatedManagerRouteChildren {
  AuthenticatedManagerIndexRoute: typeof AuthenticatedManagerIndexRoute
}

const AuthenticatedManagerRouteChildren: AuthenticatedManagerRouteChildren = {
  AuthenticatedManagerIndexRoute: AuthenticatedManagerIndexRoute,
}

const AuthenticatedManagerRouteWithChildren =
  AuthenticatedManagerRoute._addFileChildren(AuthenticatedManagerRouteChildren)

interface AuthenticatedSalesRouteChildren {
  AuthenticatedSalesIndexRoute: typeof AuthenticatedSalesIndexRoute
}

const AuthenticatedSalesRouteChildren: AuthenticatedSalesRouteChildren = {
  AuthenticatedSalesIndexRoute: AuthenticatedSalesIndexRoute,
}

const AuthenticatedSalesRouteWithChildren =
  AuthenticatedSalesRoute._addFileChildren(AuthenticatedSalesRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDirectionRoute: typeof AuthenticatedDirectionRouteWithChildren
  AuthenticatedEspaceAcheteurRoute: typeof AuthenticatedEspaceAcheteurRoute
  AuthenticatedManagerRoute: typeof AuthenticatedManagerRouteWithChildren
  AuthenticatedMesCommissionsRoute: typeof AuthenticatedMesCommissionsRoute
  AuthenticatedMesDemandesRoute: typeof AuthenticatedMesDemandesRoute
  AuthenticatedMesDemandesClientsRoute: typeof AuthenticatedMesDemandesClientsRoute
  AuthenticatedMesEchangesRoute: typeof AuthenticatedMesEchangesRoute
  AuthenticatedMonLienRoute: typeof AuthenticatedMonLienRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedSalesRoute: typeof AuthenticatedSalesRouteWithChildren
  AuthenticatedOpportunitiesIdRoute: typeof AuthenticatedOpportunitiesIdRoute
  AuthenticatedOpportunitiesNewRoute: typeof AuthenticatedOpportunitiesNewRoute
  AuthenticatedOpportunitiesSuccessIdRoute: typeof AuthenticatedOpportunitiesSuccessIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDirectionRoute: AuthenticatedDirectionRouteWithChildren,
  AuthenticatedEspaceAcheteurRoute: AuthenticatedEspaceAcheteurRoute,
  AuthenticatedManagerRoute: AuthenticatedManagerRouteWithChildren,
  AuthenticatedMesCommissionsRoute: AuthenticatedMesCommissionsRoute,
  AuthenticatedMesDemandesRoute: AuthenticatedMesDemandesRoute,
  AuthenticatedMesDemandesClientsRoute: AuthenticatedMesDemandesClientsRoute,
  AuthenticatedMesEchangesRoute: AuthenticatedMesEchangesRoute,
  AuthenticatedMonLienRoute: AuthenticatedMonLienRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedSalesRoute: AuthenticatedSalesRouteWithChildren,
  AuthenticatedOpportunitiesIdRoute: AuthenticatedOpportunitiesIdRoute,
  AuthenticatedOpportunitiesNewRoute: AuthenticatedOpportunitiesNewRoute,
  AuthenticatedOpportunitiesSuccessIdRoute:
    AuthenticatedOpportunitiesSuccessIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface ChercherUnVehiculeRouteChildren {
  ChercherUnVehiculeMerciRoute: typeof ChercherUnVehiculeMerciRoute
  ChercherUnVehiculeIndexRoute: typeof ChercherUnVehiculeIndexRoute
}

const ChercherUnVehiculeRouteChildren: ChercherUnVehiculeRouteChildren = {
  ChercherUnVehiculeMerciRoute: ChercherUnVehiculeMerciRoute,
  ChercherUnVehiculeIndexRoute: ChercherUnVehiculeIndexRoute,
}

const ChercherUnVehiculeRouteWithChildren =
  ChercherUnVehiculeRoute._addFileChildren(ChercherUnVehiculeRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  CguRoute: CguRoute,
  CgvRoute: CgvRoute,
  ChercherUnVehiculeRoute: ChercherUnVehiculeRouteWithChildren,
  ConfidentialiteRoute: ConfidentialiteRoute,
  CookiesRoute: CookiesRoute,
  MentionsLegalesRoute: MentionsLegalesRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  VehiculesIdRoute: VehiculesIdRoute,
  VehiculesIndexRoute: VehiculesIndexRoute,
  ApiPublicAffiliateClickRoute: ApiPublicAffiliateClickRoute,
  ApiPublicAssistantRoute: ApiPublicAssistantRoute,
  ApiPublicBuyerLeadsRoute: ApiPublicBuyerLeadsRoute,
  ApiPublicSignupCheckRoute: ApiPublicSignupCheckRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
