-- TM-011: normalize workflow-child authorization to the parent opportunity.
--
-- This migration addresses three legacy policy families:
-- - opportunity_status_history: staff read must inherit parent pipeline scope;
-- - information_requests: staff read must inherit parent scope and platform_admin must
--   match the trusted-admin contract already enforced by server code;
-- - opportunity_activities: internal CRM activity must not leak to the seller, while
--   legitimate writable staff must be able to add activity on rows in their scope.

-- ---------------------------------------------------------------------------
-- Opportunity status history: generated by trusted triggers, read through parent.
-- ---------------------------------------------------------------------------
DROP POLICY IF EXISTS status_history_select_owner_or_admin ON public.opportunity_status_history;
DROP POLICY IF EXISTS opp_status_history_select_parent_scoped ON public.opportunity_status_history;

CREATE POLICY opp_status_history_select_parent_scoped
ON public.opportunity_status_history
FOR SELECT TO authenticated
USING (
  EXISTS (
    SELECT 1
    FROM public.vehicle_opportunities AS opp
    WHERE opp.id = opportunity_status_history.vehicle_opportunity_id
      AND (
        opp.partenaire_id = auth.uid()
        OR (
          opp.status <> 'brouillon'::public.opportunity_status
          AND private.can_read_pipeline_record(
            auth.uid(),
            opp.assigned_sales_agent_id,
            opp.assigned_group_id,
            COALESCE(opp.assigned_group, 'purchase'::public.staff_group)
          )
        )
      )
  )
);

-- ---------------------------------------------------------------------------
-- Information requests: parent-scoped read; trusted admin writes remain explicit.
-- ---------------------------------------------------------------------------
DROP POLICY IF EXISTS info_req_select_owner_or_admin ON public.information_requests;
DROP POLICY IF EXISTS info_req_select_parent_scoped ON public.information_requests;
DROP POLICY IF EXISTS info_req_admin_insert ON public.information_requests;
DROP POLICY IF EXISTS info_req_update_admin ON public.information_requests;
DROP POLICY IF EXISTS info_req_insert_trusted_admin ON public.information_requests;
DROP POLICY IF EXISTS info_req_update_trusted_admin ON public.information_requests;

CREATE POLICY info_req_select_parent_scoped
ON public.information_requests
FOR SELECT TO authenticated
USING (
  EXISTS (
    SELECT 1
    FROM public.vehicle_opportunities AS opp
    WHERE opp.id = information_requests.vehicle_opportunity_id
      AND (
        opp.partenaire_id = auth.uid()
        OR (
          opp.status <> 'brouillon'::public.opportunity_status
          AND private.can_read_pipeline_record(
            auth.uid(),
            opp.assigned_sales_agent_id,
            opp.assigned_group_id,
            COALESCE(opp.assigned_group, 'purchase'::public.staff_group)
          )
        )
      )
  )
);

CREATE POLICY info_req_insert_trusted_admin
ON public.information_requests
FOR INSERT TO authenticated
WITH CHECK (
  private.has_any_role(
    auth.uid(),
    ARRAY['admin'::public.app_role, 'platform_admin'::public.app_role]
  )
);

CREATE POLICY info_req_update_trusted_admin
ON public.information_requests
FOR UPDATE TO authenticated
USING (
  private.has_any_role(
    auth.uid(),
    ARRAY['admin'::public.app_role, 'platform_admin'::public.app_role]
  )
)
WITH CHECK (
  private.has_any_role(
    auth.uid(),
    ARRAY['admin'::public.app_role, 'platform_admin'::public.app_role]
  )
);

CREATE OR REPLACE FUNCTION public.tg_info_req_owner_guard()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO 'public'
AS $function$
BEGIN
  IF auth.role() = 'service_role'
     OR private.has_any_role(
       auth.uid(),
       ARRAY['admin'::public.app_role, 'platform_admin'::public.app_role]
     ) THEN
    RETURN NEW;
  END IF;

  IF NEW.message IS DISTINCT FROM OLD.message
     OR NEW.admin_id IS DISTINCT FROM OLD.admin_id
     OR NEW.vehicle_opportunity_id IS DISTINCT FROM OLD.vehicle_opportunity_id
     OR NEW.created_at IS DISTINCT FROM OLD.created_at THEN
    RAISE EXCEPTION 'information_request: partenaire cannot modify these fields';
  END IF;

  IF OLD.status = 'answered'::public.info_request_status THEN
    RAISE EXCEPTION 'information_request: answered response is immutable to partenaire';
  END IF;

  IF NEW.status <> 'answered'::public.info_request_status THEN
    RAISE EXCEPTION 'information_request: partenaire can only set status to answered';
  END IF;

  -- Canonicalize audit timestamps at the database boundary instead of trusting
  -- caller-provided times from a browser session.
  NEW.answered_at := now();
  IF NEW.response IS DISTINCT FROM OLD.response AND NEW.response IS NOT NULL THEN
    NEW.response_at := now();
  ELSIF NEW.response IS NULL THEN
    NEW.response_at := NULL;
  END IF;

  RETURN NEW;
END;
$function$;

-- ---------------------------------------------------------------------------
-- Opportunity activities: internal CRM rows are not partner-readable.
-- ---------------------------------------------------------------------------
DROP POLICY IF EXISTS activities_select_admin_or_owner ON public.opportunity_activities;
DROP POLICY IF EXISTS activities_insert_admin ON public.opportunity_activities;
DROP POLICY IF EXISTS activities_insert_owner_note ON public.opportunity_activities;
DROP POLICY IF EXISTS activities_update_admin ON public.opportunity_activities;
DROP POLICY IF EXISTS activities_delete_admin ON public.opportunity_activities;
DROP POLICY IF EXISTS activities_select_parent_scoped ON public.opportunity_activities;
DROP POLICY IF EXISTS activities_insert_staff_scoped ON public.opportunity_activities;
DROP POLICY IF EXISTS activities_insert_partner_note_editable ON public.opportunity_activities;
DROP POLICY IF EXISTS activities_update_trusted_admin ON public.opportunity_activities;
DROP POLICY IF EXISTS activities_delete_trusted_admin ON public.opportunity_activities;

CREATE POLICY activities_select_parent_scoped
ON public.opportunity_activities
FOR SELECT TO authenticated
USING (
  EXISTS (
    SELECT 1
    FROM public.vehicle_opportunities AS opp
    WHERE opp.id = opportunity_activities.vehicle_opportunity_id
      AND (
        (
          opp.status <> 'brouillon'::public.opportunity_status
          AND private.can_read_pipeline_record(
            auth.uid(),
            opp.assigned_sales_agent_id,
            opp.assigned_group_id,
            COALESCE(opp.assigned_group, 'purchase'::public.staff_group)
          )
        )
        OR (
          opp.partenaire_id = auth.uid()
          AND opportunity_activities.kind = 'note'
          AND opportunity_activities.author_id = auth.uid()
        )
      )
  )
);

CREATE POLICY activities_insert_staff_scoped
ON public.opportunity_activities
FOR INSERT TO authenticated
WITH CHECK (
  author_id = auth.uid()
  AND private.has_any_role(
    auth.uid(),
    ARRAY[
      'admin'::public.app_role,
      'platform_admin'::public.app_role,
      'sales_manager'::public.app_role,
      'sales_agent'::public.app_role,
      'external_agent'::public.app_role
    ]
  )
  AND EXISTS (
    SELECT 1
    FROM public.vehicle_opportunities AS opp
    WHERE opp.id = opportunity_activities.vehicle_opportunity_id
      AND opp.status <> 'brouillon'::public.opportunity_status
      AND private.can_write_pipeline_record(
        auth.uid(),
        opp.assigned_sales_agent_id,
        opp.assigned_group_id,
        COALESCE(opp.assigned_group, 'purchase'::public.staff_group)
      )
  )
);

CREATE POLICY activities_insert_partner_note_editable
ON public.opportunity_activities
FOR INSERT TO authenticated
WITH CHECK (
  kind = 'note'
  AND author_id = auth.uid()
  AND EXISTS (
    SELECT 1
    FROM public.vehicle_opportunities AS opp
    WHERE opp.id = opportunity_activities.vehicle_opportunity_id
      AND opp.partenaire_id = auth.uid()
      AND (
        (
          private.has_role(auth.uid(), 'partenaire'::public.app_role)
          AND private.get_partner_kind(auth.uid()) = 'seller'::public.partner_kind
        )
        OR private.is_external_agent(auth.uid())
      )
      AND (
        opp.status = 'brouillon'::public.opportunity_status
        OR opp.owner_side = 'partenaire'::public.opportunity_owner_side
      )
  )
);

CREATE POLICY activities_update_trusted_admin
ON public.opportunity_activities
FOR UPDATE TO authenticated
USING (
  private.has_any_role(
    auth.uid(),
    ARRAY['admin'::public.app_role, 'platform_admin'::public.app_role]
  )
)
WITH CHECK (
  private.has_any_role(
    auth.uid(),
    ARRAY['admin'::public.app_role, 'platform_admin'::public.app_role]
  )
);

CREATE POLICY activities_delete_trusted_admin
ON public.opportunity_activities
FOR DELETE TO authenticated
USING (
  private.has_any_role(
    auth.uid(),
    ARRAY['admin'::public.app_role, 'platform_admin'::public.app_role]
  )
);
